# Generated by Django 5.1.2 on 2025-03-13 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('team_members', models.TextField(max_length=255)),
                ('tech_stack', models.TextField(max_length=255)),
                ('projecturl', models.TextField(max_length=255)),
                ('achivements', models.TextField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('research', 'Research'), ('project', 'Project')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin')], editable=False, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
