# Generated by Django 5.1.2 on 2025-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_top_6',
            field=models.BooleanField(default=False),
        ),
    ]
