# Generated by Django 5.1.2 on 2025-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
