# Generated by Django 5.1.2 on 2025-03-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0002_alter_form_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('student', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
