# Generated by Django 5.1.2 on 2025-03-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0002_form_is_top_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
