# Generated by Django 5.1.2 on 2025-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0003_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='top_2',
            field=models.BooleanField(default=False),
        ),
    ]
