# Generated by Django 5.1.2 on 2025-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0006_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='form_documents/'),
        ),
    ]
