# Generated by Django 5.1.2 on 2025-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0007_form_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='team_members',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
