# Generated by Django 5.1.2 on 2025-05-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='keep_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
