# Generated by Django 5.1.2 on 2025-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_keep_anonymous_feedback_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='parent_name',
            field=models.CharField(default='default_test', max_length=255),
            preserve_default=False,
        ),
    ]
