# Generated by Django 5.1.2 on 2025-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInEmbeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_urls', models.TextField(help_text='Paste LinkedIn embed URLs separated by commas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LinkedIn Embeds',
                'verbose_name_plural': 'LinkedIn Embeds',
            },
        ),
    ]
