# Generated by Django 5.1.2 on 2025-04-01 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_embed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinembeds',
            name='embed_urls',
        ),
        migrations.AddField(
            model_name='linkedinembeds',
            name='embed_code',
            field=models.TextField(default=django.utils.timezone.now, help_text='Paste LinkedIn embed iframe HTML code separated by commas'),
            preserve_default=False,
        ),
    ]
