# Generated by Django 5.1.2 on 2025-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registrationotp_alter_user_is_verified_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationotp',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
    ]
