# Generated by Django 5.1.2 on 2025-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_registrationotp_user_type_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationotp',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('PARENT', 'Parent')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('PARENT', 'Parent'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
    ]
