# Generated by Django 5.1.2 on 2025-05-25 06:50

from django.db import migrations, models

def generate_username_ids(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    for user in User.objects.all():
        user.username_id = f"{user.email.lower()}__{user.user_type.upper()}"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_registrationotp_user_type_alter_user_user_type'),
    ]

    operations = [
        # Step 1: Add username_id as nullable first
        migrations.AddField(
            model_name='user',
            name='username_id',
            field=models.CharField(max_length=100, unique=True, null=True, editable=False),
        ),

        # Step 2: Backfill username_id
        migrations.RunPython(generate_username_ids),

        # Step 3: Make username_id non-nullable now that it's populated
        migrations.AlterField(
            model_name='user',
            name='username_id',
            field=models.CharField(max_length=100, unique=True, editable=False),
        ),

        # Step 4: Remove unique constraint from email
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),

        # Step 5: Add unique constraint on (email, user_type)
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'user_type')},
        ),
    ]
